"""empty message

Revision ID: 953bb691cd5c
Revises: 0763d677d453
Create Date: 2025-12-16 19:19:02.966095

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '953bb691cd5c'
down_revision = '0763d677d453'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username', sa.String(length=100), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('username')

    # ### end Alembic commands ###
